build:
    title: OutSystems 11
    input-folder: src
    output-folder: build
    related-title: See Also   
publish:
    url: https://success.outsystems.com/
    root_path: Documentation/11_x_platform
    toc_url: https://success.outsystems.com/
    toc_root_path: Documentation/11_x_platform
    skip_toc_publish: False
    skip_edit_links: True
reference:
    assemble-folder: 
        - src/ref/lang/auto
        - src/ref/apis/auto
checktoc:
    url: https://success.outsystems.com/
    root_path: ""
    mindtouch-toc-path: Documentation/11_x_platform/TOC
    auto-toc-path: Documentation/Unlisted/Technical_Communication/Wiki_Tree_11_x_platform
